# Scaffolding generated by Casein v.2.0.6

require 'test_helper'

class CaseinNumberMastersControllerTest < ActionController::TestCase
  
  test "should get index" do
    get :index
    assert_response :success
    assert_not_nil assigns(:number_masters)
  end

  test "should get new" do
    get :new
    assert_response :success
  end

  test "should create number_master" do
    assert_difference('NumberMaster.count') do
      post :create, :number_master => { }
    end

    assert_redirected_to number_master_path(assigns(:number_master))
  end

  test "should show number_master" do
    get :show, :id => number_masters(:one).id
    assert_response :success
  end

  test "should update number_master" do
    put :update, :id => number_masters(:one).id, :number_master => { }
    assert_redirected_to number_master_path(assigns(:number_master))
  end

  test "should destroy number_master" do
    assert_difference('NumberMaster.count', -1) do
      delete :destroy, :id => number_masters(:one).id
    end

    assert_redirected_to number_masters_path
  end
end
