# Scaffolding generated by Casein v.2.0.6

class CaseinRegionsController < CaseinController
 
  ## optional filters for defining usage according to casein_users access_levels
  # before_filter :needs_admin, :except => [:action1, :action2]
  # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
 
  def index
		if request.get?
			@casein_page_title = 'Regions'
			@regions = Region.paginate :all, :page => params[:page]
		end
  end
 
  def new
		if request.get?
			@casein_page_title = 'Add a new region'
    	@region = Region.new
		end
  end

  def create
    if request.post?
      @region = Region.new params[:region]
      
      unless @region.save
        flash[:warning] = 'There were problems when trying to create a new region'
        render :action => :new
        return
      end
      
      flash[:notice] = 'Region created'
    end
    redirect_to casein_regions_path
  end
  
  def show
		if request.get?
   	 @region = Region.find params[:id]
    
	    if @region.nil?
	      redirect_to casein_regions_path
	    end

			@casein_page_title = 'View region'
		end
  end
 
  def update
    if request.put?
      @region = Region.find params[:id]

      if @region
        @casein_page_title = 'Update region'

        unless @region.update_attributes params[:region]
          flash[:warning] = 'There were problems when trying to update this region'
          render :action => :show
          return
        end
        flash[:notice] = 'Region has been updated'
      end
    end

    redirect_to casein_regions_path
  end
 
  def destroy
    if request.delete?
      @region = Region.find_by_id params[:id]

      if @region
        flash[:notice] = 'Region has been deleted'
        @region.destroy
      end
    end

    redirect_to :back
  end
  
end