common :
  name : receive
  total_size :
  check_integer_position :
  file_type : csv
format :
  work_no :
    index  : 1
    value  :
    action :
  waacs_code :
    index  : 2
    value  :
    action :
  goods_code :
    index  : 3
    value  :
    action :
  location :
    index  : 4
    value  :
    action :
  announced_qty :
    index  : 5
    value  :
    action :
  goods_name :
    index  : 6
    value  :
    action :
  edi_code :
    index  : 7
    value  :
    action :
  supplier :
    index  : 8
    value  :
    action :
