# Scaffolding generated by Casein v.2.0.6

class CaseinInventoriesController < CaseinController
 
  ## optional filters for defining usage according to casein_users access_levels
  # before_filter :needs_admin, :except => [:action1, :action2]
  # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
 
  def index
		#if request.get?
			@casein_page_title = 'Inventories'
			@search = params[:search]
			@inventories = Inventory.goods_code_or_goods_name_or_location_like(@search).paginate :all, :page => params[:page]
		#end
  end
 
  def new
		if request.get?
			@casein_page_title = 'Add a new inventory'
    	@inventory = Inventory.new
		end
  end

  def create
    if request.post?
      @inventory = Inventory.new params[:inventory]
      
      unless @inventory.save
        flash[:warning] = 'There were problems when trying to create a new inventory'
        render :action => :new
        return
      end
      
      flash[:notice] = 'Inventory created'
    end
    redirect_to casein_inventories_path
  end
  
  def show
		if request.get?
   	 @inventory = Inventory.find params[:id]
    
	    if @inventory.nil?
	      redirect_to casein_inventories_path
	    end

			@casein_page_title = 'View inventory'
		end
  end
 
  def update
    if request.put?
      @inventory = Inventory.find params[:id]

      if @inventory
        @casein_page_title = 'Update inventory'

        unless @inventory.update_attributes params[:inventory]
          flash[:warning] = 'There were problems when trying to update this inventory'
          render :action => :show
          return
        end
        flash[:notice] = 'Inventory has been updated'
      end
    end

    redirect_to casein_inventories_path
  end
 
  def destroy
    if request.delete?
      @inventory = Inventory.find_by_id params[:id]

      if @inventory
        flash[:notice] = 'Inventory has been deleted'
        @inventory.destroy
      end
    end

    redirect_to :back
  end
  
end
