# Scaffolding generated by Casein v.2.0.6

class CaseinOrdersController < CaseinController
 
  ## optional filters for defining usage according to casein_users access_levels
  # before_filter :needs_admin, :except => [:action1, :action2]
  # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
 
  def index
		#if request.get?
			@casein_page_title = 'Orders'
			@search = params[:search]
			@orders = Order.order_no_or_store_code_or_customer_code_like(@search).paginate :all, :page => params[:page]
		#end
  end
	
  def search 
		redirect_to :action => 'index'
  end
 
  def new
		if request.get?
			@casein_page_title = 'Add a new order'
    	@order = Order.new
		end
  end

  def create
    if request.post?
      @order = Order.new params[:order]
      
      unless @order.save
        flash[:warning] = 'There were problems when trying to create a new order'
        render :action => :new
        return
      end
      
      flash[:notice] = 'Order created'
    end
    redirect_to casein_orders_path
  end
  
  def show
		if request.get?
   	 @order = Order.find params[:id]
    
	    if @order.nil?
	      redirect_to casein_orders_path
	    end

			@casein_page_title = 'View order'
		end
  end
 
  def update
    if request.put?
      @order = Order.find params[:id]

      if @order
        @casein_page_title = 'Update order'

        unless @order.update_attributes params[:order]
          flash[:warning] = 'There were problems when trying to update this order'
          render :action => :show
          return
        end
        flash[:notice] = 'Order has been updated'
      end
    end

    redirect_to casein_orders_path
  end
 
  def destroy
    if request.delete?
      @order = Order.find_by_id params[:id]

      if @order
        flash[:notice] = 'Order has been deleted'
        @order.destroy
      end
    end

    redirect_to :back
  end
  
end
