common :
  name : ship_order
  total_size : 136
  check_integer_position :
  file_type : fix
format :
  work_no :
    start  : 1
    size   : 10
    view   :
    action :
  work_line_no :
    start  : 11
    size   : 5
    view   :
    action :
  location :
    start  : 16
    size   : 10
    view   :
    action :
  goods_code :
    start  : 26
    size   : 20
    view   :
    action :
  order_qty :
    start  : 46
    size   : 10
    view   :
    action :
  result_qty :
    start  : 56
    size   : 10
    view   :
    action :
  user_code :
    start  : 66
    size   : 10
    view   :
    action :
  goods_name :
    start  : 76
    size   : 30
    view   : 
    action :
  delivery_name :
    start  : 106
    size   : 30
    view   :
    action :
